services:
  web:
    volumes:
      - ./public:/workspace/public
      - ./db:/workspace/db
      - .:/workspace/all
  db-gui:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=admin
