# dbがpushされたときに起動するドキュメント生成用ワークフロー
name: Generate Documentation

on:
  push:
    branches:
        - db
    paths:
        - 'db/**'
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.x'

        - name: install GNU make
          run: |
            sudo apt-get update
            sudo apt-get install make

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            python -m pip install --upgrade pipenv
            PATH=$HOME/.local/bin:$PATH
            pipenv install --dev

        - name: Build
          run: make doc

        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          with:
            personal_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./doc/build/html
