name: Docker Image CI(ビルドテスト)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # 手動実行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Buildx setting
        uses: docker/setup-buildx-action@v3
      - name: Test Build
        run: docker build --tag test env
