name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Buildx setting
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    #- name: Build the Docker image
    #  run: docker buildx build --tag densukest/xampp-devenv  --push env
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: densukest/xampp-devenv:latest
        platforms: linux/amd64,linux/arm64
        context: env
